FROM public.ecr.aws/lambda/python:3.8

WORKDIR /app

ENV PYTHONPATH /app
ENV PATH="/app/bin:${PATH}"

COPY requirements-predict.txt ./requirements.txt
# RUN python -m pip install --upgrade pip
RUN pip install --no-cache -r requirements.txt
COPY predict.py ./
COPY module module

# sls does not support docker build --squash, i filed an issue:
# https://github.com/serverless/serverless/issues/10712
RUN pip install --no-cache-dir -r requirements.txt
