##
## This software is Copyright ©️ 2020 The University of Southern California. All Rights Reserved. 
## Permission to use, copy, modify, and distribute this software and its documentation for educational, research and non-profit purposes, without fee, and without a written agreement is hereby granted, provided that the above copyright notice and subject to the full license file found in the root of this software deliverable. Permission to make commercial use of this software may be obtained by contacting:  USC Stevens Center for Innovation University of Southern California 1150 S. Olive Street, Suite 2300, Los Angeles, CA 90115, USA Email: accounting@stevens.usc.edu
##
## The full terms of this copyright and license should always be found in the root directory of this software deliverable as "license.txt" and if these terms are not found with this software, please contact the USC Stevens Center for the full license.
##

# This file is the main config file for your service.
#
# For full config options, check the docs:
#    docs.serverless.com
#

service: mentor-classifier-service

# pin the service to only deploy with a specific Serverless version
frameworkVersion: '2'
variablesResolutionMode: 20210326

plugins:
  - serverless-deployment-bucket
  - serverless-layers

custom:
  stages:
    offline:
      LOG_LEVEL: 'trace'
      GRAPHQL_ENDPOINT: 'http://127.0.0.1:3001/graphql'
      IS_SENTRY_ENABLED: false
    dev:
      # TODO cors
      LOG_LEVEL: 'trace'
      IS_SENTRY_ENABLED: false
      # v2 is hardcoded, we could use fallback stages instead
      GRAPHQL_ENDPOINT: 'https://v2.mentorpal.org/graphql'
      API_SECRET: '${ssm:/mentorpal/v2/shared/api_secret}'
      ALERT_SNS_ARN: ${ssm:/mentorpal/v2/shared/sns_alert_topic_arn}
    qa:
      LOG_LEVEL: 'debug'
      IS_SENTRY_ENABLED: true
      GRAPHQL_ENDPOINT: 'https://v2.mentorpal.org/graphql'
      API_SECRET: '${ssm:/mentorpal/v2/shared/api_secret}'
      ALERT_SNS_ARN: ${ssm:/mentorpal/v2/shared/sns_alert_topic_arn}
    prod:
      LOG_LEVEL: 'info'
      IS_SENTRY_ENABLED: true
      GRAPHQL_ENDPOINT: 'https://careerfair.mentorpal.org/graphql'
      # TODO
      # ALERT_SNS_ARN: ${ssm:/mentorpal/careerfair/shared/sns_alert_topic_arn}

  # serverless-layers requires a deployment bucket to be created before deploying this stack
  serverless-layers:
    - dependencies:
        layersDeploymentBucket: ${self:provider.deploymentBucket.name}
        dependenciesPath: ./requirements.txt
        compatibleRuntimes:
          - python3.8
        functions:
          - http_train
          - http_train_status
          - http_training_data

provider:
  name: aws
  stage: ${opt:stage, 'dev'} # stage is dev unless otherwise specified with --stage flag
  lambdaHashingVersion: 20201221
  runtime: python3.8
  deploymentBucket:
    name: '${self:service}-sls-deploy-${self:provider.stage}'
    blockPublicAccess: true
    serverSideEncryption: AES256
    versioning: false
  stackTags:
    ENVIRONMENT: ${self:provider.stage}
    PROJECT: ${self:service}-${self:provider.stage}
    REPOSITORY: mentor-classifier-service
  ecr:
    # In this section you can define images that will be built locally and uploaded to ECR
    images:
      train:
        path: ./
        file: Dockerfile
  endpointType: regional
  apiGateway:
    minimumCompressionSize: 1024
    usagePlan:
      throttle:
        burstLimit: 100
        rateLimit: 10

  tracing:
    lambda: true
    apiGateway: true
  logRetentionInDays: 30
  logs:
    restApi:
      # Enables HTTP access logs (default: true)
      accessLogging: true
      # # Log format to use for access logs
      # format: 'requestId: $context.requestId'
      # Enable execution logging (default: true)
      executionLogging: true
      level: INFO  # INFO or ERROR
      # Log full requests/responses for execution logging (default: true)
      fullExecutionData: false
  region: us-east-1
  architecture: x86_64 # in case deploy is run on a different architecture (apple arm...)
  environment:
    STAGE: ${self:provider.stage}
    PYTHON_ENV: careerfair-${self:provider.stage}
    GRAPHQL_ENDPOINT: ${self:custom.stages.${self:provider.stage}.GRAPHQL_ENDPOINT}
    API_SECRET: ${self:custom.stages.${self:provider.stage}.API_SECRET}
    IS_SENTRY_ENABLED: ${self:custom.stages.${self:provider.stage}.IS_SENTRY_ENABLED}
    SENTRY_DSN_MENTOR_CLASSIFIER: '${ssm:/mentorpal/upload/sentry_dsn}'
    SHARED_ROOT: '/app/shared' # as defined in Dockerfile
    MODELS_BUCKET: classifier-models-${self:provider.stage}
    JOBS_TABLE_NAME: classifier-jobs-${self:provider.stage}
    JOBS_SQS_NAME: classifier-jobs-${self:provider.stage}
  iam:
    role:
      statements:
      # todo create dedicated roles for each function for increased security
        - Effect: "Allow"
          Action:
            - "s3:PutObject"
            - "s3:GetObject"
          Resource:
            - 'arn:aws:s3:::${self:provider.environment.MODELS_BUCKET}/*'
        - Effect: "Allow"
          Action:
            - dynamodb:GetItem
            - dynamodb:PutItem
            - dynamodb:UpdateItem
          Resource:
            Fn::GetAtt: [JobsTable, Arn]
        - Effect: "Allow"
          Action:
            - sqs:SendMessage
            - sqs:GetQueueUrl
          Resource:
            Fn::GetAtt: [TrainQueue, Arn]

package:
 individually: false
 patterns:
    # exclude everything:
     - '!./**'
    # and then add back in only the files we need:
     - '*.py'
     - 'module/**'

functions:
  http_train:
    handler: train.handler
    memorySize: 1024
    timeout: 30
    events:
      - http:
          path: /train
          method: post
  http_train_status:
    handler: status.handler
    memorySize: 512
    timeout: 10
    events:
      - http:
          path: /train/status/{id}
          method: get
          request:
            parameters:
              paths:
                id: true
  sqs_train:
    image:
      name: train
      command:
        - trainjob.handler
    memorySize: 8192
    timeout: 600
    events:
      - sqs:
          arn:
            Fn::GetAtt: [TrainQueue, Arn]
          batchSize: 1
  http_answer:
    image:
      name: train
      command:
        - predict.handler
    memorySize: 8192
    timeout: 120
    events:
      - http:
          path: /questions
          method: get
          request:
            parameters:
              querystrings:
                mentor: true
                query: true
  http_training_data:
    handler: trainingdata.handler
    memorySize: 2048
    timeout: 30
    events:
      - http:
          path: /trainingdata/{mentor}
          method: get
          request:
            parameters:
              paths:
                mentor: true


resources:
  Conditions:
    CreateCloudWatchAlarm:
      Fn::Or:
        - Fn::Equals: ['${self:provider.stage}', 'qa']
        - Fn::Equals: ['${self:provider.stage}', 'prod']
  Resources:
    TrainDLQ:
      Type: AWS::SQS::Queue
      Properties:
        DelaySeconds: 30
        QueueName: classifier-jobs-dlq-${self:provider.stage}
        MessageRetentionPeriod: 1209600 # max 14 days, default is 4 days
    TrainQueue:
      Type: AWS::SQS::Queue
      Properties:
        # https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-properties-sqs-queues.html
        QueueName:  ${self:provider.environment.JOBS_SQS_NAME}
        VisibilityTimeout: 800 # AWS recommends 6 times lambdas timeout
        RedrivePolicy:
          deadLetterTargetArn:
            Fn::GetAtt: [TrainDLQ, Arn]
          maxReceiveCount: 5 # AWS recommends minimum 5
    
    TrainedModelsBucket:
      Type: AWS::S3::Bucket
      Properties:
        BucketName: ${self:provider.environment.MODELS_BUCKET}

    JobsTable:
      Type: AWS::DynamoDB::Table
      DeletionPolicy: Delete
      UpdateReplacePolicy: Delete
      Properties:
        TableName: ${self:provider.environment.JOBS_TABLE_NAME}
        BillingMode: PAY_PER_REQUEST
        AttributeDefinitions:
          - AttributeName: id
            AttributeType: S
        KeySchema:
          - AttributeName: id
            KeyType: HASH
        # to cleanup jobs after a while set this attribute as a number
        TimeToLiveSpecification: 
          AttributeName: ttl
          Enabled: true

    TrainDLQAlarm:
      Type: AWS::CloudWatch::Alarm
      Condition: CreateCloudWatchAlarm
      Properties:
        ActionsEnabled: true
        AlarmName: 'Number of failed train jobs ${self:resources.Resources.TrainDLQ.Properties.QueueName}'
        AlarmDescription: 'Number of failed train jobs greater than zero'
        Namespace: 'AWS/SQS'
        Statistic: 'Sum'
        MetricName: 'ApproximateNumberOfMessagesVisible'
        ComparisonOperator: 'GreaterThanThreshold'
        EvaluationPeriods: 1
        Period: 300 # 5 minutes in seconds
        Threshold: 0
        TreatMissingData: 'notBreaching'
        Dimensions:
          - Name: QueueName
            Value: ${self:resources.Resources.TrainDLQ.Properties.QueueName}
        AlarmActions:
          - ${self:custom.stages.${self:provider.stage}.ALERT_SNS_ARN}
        OKActions:
          - ${self:custom.stages.${self:provider.stage}.ALERT_SNS_ARN}
