version: 0.2

env:
  git-credential-helper: yes
  variables:
    SENTRY_ORG: 'usc-ict-ls'
    SENTRY_PROJECT: 'mentor-classifier'

phases:
  install:
    runtime-versions:
      nodejs: 14
    commands:
      - pyenv global $PYTHON_38_VERSION
      - python3 -m venv /root/venv
      - . /root/venv/bin/activate
      - pip3 install pytest && pip3 install poetry
      - poetry install --no-root
      # Installing git lfs
      - curl -OJL https://github.com/git-lfs/git-lfs/releases/download/v3.1.4/git-lfs-linux-amd64-v3.1.4.tar.gz
      - tar xzf git-lfs-linux-amd64-v3.1.4.tar.gz
      - ./install.sh
      - n 16 # workaround https://github.com/aws/aws-codebuild-docker-images/issues/490
      - NODE_ENV=dev npm ci

  build:
    commands:
      - echo cloning repo
      - git clone https://github.com/mentorpal/classifier-service.git
      - echo Checking formatting
      - flake8 .
      # TODO 
      # - echo Running tests

artifacts:
  files:
    - '**/*'
  enable-symlinks: yes
cache:
  paths:
    - '/root/venv/**/*'
    - '/root/.cache/pip/**/*'
    - '/root/.cache/pypoetry/virtualenvs/**/*'
